version: '2'

services:
  spark:
    image: docker.io/bitnami/spark:3
    volumes:
        - D:/spark-setup/spark-docker/sampledata:/mnt/sampledata
        - D:/spark-setup/spark-docker/jars:/opt/bitnami/spark/jars
        - D:/spark-setup/spark-docker/conf:/opt/bitnami/spark/conf
        - D:/spark-setup/spark-docker/ivy2:/opt/bitnami/spark/.ivy2
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
  spark-worker-1:
    image: docker.io/bitnami/spark:3
    volumes:
        - D:/spark-setup/spark-docker/sampledata:/mnt/sampledata
        - D:/spark-setup/spark-docker/jars:/opt/bitnami/spark/jars
        - D:/spark-setup/spark-docker/conf:/opt/bitnami/spark/conf
        - D:/spark-setup/spark-docker/ivy2:/opt/bitnami/spark/.ivy2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-2:
    image: docker.io/bitnami/spark:3
    volumes:
        - D:/spark-setup/spark-docker/sampledata:/mnt/sampledata
        - D:/spark-setup/spark-docker/jars:/opt/bitnami/spark/jars
        - D:/spark-setup/spark-docker/conf:/opt/bitnami/spark/conf
        - D:/spark-setup/spark-docker/ivy2:/opt/bitnami/spark/.ivy2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no